[package]
name = "workshop"
version = "0.1.0"
edition = "2021"
# TODO: cleanup
[dependencies]
#makepad-widgets = { path = "../../code/rust/futurewei/mkpd/makepad/widgets"}
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }